services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crud-go-backend
    environment:
      - DB_CONN=postgres://postgres:Password123@host.minikube.internal:5432/clidb?sslmode=disable
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crud-nextjs-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

