apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:v1
        imagePullPolicy: Never 
        ports:
        - containerPort: 3000 # Matches the internal port of your container
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "http://10.106.218.203:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80       # External port for HTTP web traffic
    targetPort: 3000 # Internal container port
  type: LoadBalancer # Automatically provisions a public Azure IP address

