source 'https://rubygems.org'

gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.6'
gem 'puma', '~> 6.0'
gem 'bootsnap', '>= 1.18', require: false
gem 'rack-cors'

group :development do
  gem 'listen', '~> 3.7'
end

group :test do
  gem 'minitest', '~> 5.0'
end
